/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDnsZoneRequest {
    /// The domain of the DNS zone to create
    #[serde(rename = "domain")]
    pub domain: String,
    /// The subdomain of the DNS zone to create
    #[serde(rename = "subdomain")]
    pub subdomain: String,
    /// The project ID where the DNS zone will be created
    #[serde(rename = "project_id")]
    pub project_id: String,
}

impl CreateDnsZoneRequest {
    pub fn new(domain: String, subdomain: String, project_id: String) -> CreateDnsZoneRequest {
        CreateDnsZoneRequest {
            domain,
            subdomain,
            project_id,
        }
    }
}
