/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateGroupRequest {
    /// ID of organization linked to the group
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    /// Name of the group to create (max length is 64 chars). MUST be unique inside an organization
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the group to create (max length is 200 chars)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CreateGroupRequest {
    pub fn new(organization_id: String, name: String) -> CreateGroupRequest {
        CreateGroupRequest {
            organization_id,
            name,
            description: None,
        }
    }
}
