/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateClusterRequestAutoscalerConfigScaleDownUtilizationThreshold : Node utilization level, defined as sum of requested resources divided by capacity, below which a node can be considered for scale down

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateClusterRequestAutoscalerConfigScaleDownUtilizationThreshold {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i64>,
}

impl CreateClusterRequestAutoscalerConfigScaleDownUtilizationThreshold {
    /// Node utilization level, defined as sum of requested resources divided by capacity, below which a node can be considered for scale down
    pub fn new() -> CreateClusterRequestAutoscalerConfigScaleDownUtilizationThreshold {
        CreateClusterRequestAutoscalerConfigScaleDownUtilizationThreshold { value: None }
    }
}
