/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestoreDatabaseBackupRequest {
    /// Defines the destination database in order to restore into a specified database, the default destination is set to the origin database of the backup
    #[serde(
        rename = "database_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub database_name: Option<Option<String>>,
    /// Defines the rdb instance where the backup has to be restored
    #[serde(rename = "instance_id")]
    pub instance_id: String,
}

impl RestoreDatabaseBackupRequest {
    pub fn new(instance_id: String) -> RestoreDatabaseBackupRequest {
        RestoreDatabaseBackupRequest {
            database_name: None,
            instance_id,
        }
    }
}
