/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodBaremetalPeriodV1PeriodListOptionsResponse {
    /// Total count of matching options
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    /// Options that match filters
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<crate::models::ScalewayPeriodBaremetalPeriodV1PeriodOption>>,
}

impl ScalewayPeriodBaremetalPeriodV1PeriodListOptionsResponse {
    pub fn new() -> ScalewayPeriodBaremetalPeriodV1PeriodListOptionsResponse {
        ScalewayPeriodBaremetalPeriodV1PeriodListOptionsResponse {
            total_count: None,
            options: None,
        }
    }
}
