/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScalewayBaremetalV1OsServicePassword : Define the password requirements to install the service

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayBaremetalV1OsServicePassword {
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(
        rename = "default_value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_value: Option<Option<String>>,
}

impl ScalewayBaremetalV1OsServicePassword {
    /// Define the password requirements to install the service
    pub fn new() -> ScalewayBaremetalV1OsServicePassword {
        ScalewayBaremetalV1OsServicePassword {
            editable: None,
            required: None,
            default_value: None,
        }
    }
}
