/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodRdbPeriodV1PeriodDeleteInstanceSettingsResponse {
    /// Settings names to delete from the instance
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Vec<crate::models::ScalewayPeriodRdbPeriodV1PeriodInstanceSetting>>,
}

impl ScalewayPeriodRdbPeriodV1PeriodDeleteInstanceSettingsResponse {
    pub fn new() -> ScalewayPeriodRdbPeriodV1PeriodDeleteInstanceSettingsResponse {
        ScalewayPeriodRdbPeriodV1PeriodDeleteInstanceSettingsResponse { settings: None }
    }
}
