/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodRdbPeriodV1PeriodListNodeTypesResponse {
    /// Types of the node
    #[serde(rename = "node_types", skip_serializing_if = "Option::is_none")]
    pub node_types: Option<Vec<crate::models::ScalewayPeriodRdbPeriodV1PeriodNodeType>>,
    /// Total count of node-types available
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
}

impl ScalewayPeriodRdbPeriodV1PeriodListNodeTypesResponse {
    pub fn new() -> ScalewayPeriodRdbPeriodV1PeriodListNodeTypesResponse {
        ScalewayPeriodRdbPeriodV1PeriodListNodeTypesResponse {
            node_types: None,
            total_count: None,
        }
    }
}
