/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodDomainPeriodV2beta1PeriodImportRawDnsZoneRequestPeriodTsigKey {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
}

impl ScalewayPeriodDomainPeriodV2beta1PeriodImportRawDnsZoneRequestPeriodTsigKey {
    pub fn new() -> ScalewayPeriodDomainPeriodV2beta1PeriodImportRawDnsZoneRequestPeriodTsigKey {
        ScalewayPeriodDomainPeriodV2beta1PeriodImportRawDnsZoneRequestPeriodTsigKey {
            name: None,
            key: None,
            algorithm: None,
        }
    }
}
