/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodInstancePeriodV1PeriodServerActionRequestPeriodVolumeBackupTemplate {
    /// Overrides the volume_type of the snapshot for this volume. If omitted, the volume type of the original volume will be used.
    #[serde(rename = "volume_type", skip_serializing_if = "Option::is_none")]
    pub volume_type: Option<VolumeType>,
}

impl ScalewayPeriodInstancePeriodV1PeriodServerActionRequestPeriodVolumeBackupTemplate {
    pub fn new() -> ScalewayPeriodInstancePeriodV1PeriodServerActionRequestPeriodVolumeBackupTemplate
    {
        ScalewayPeriodInstancePeriodV1PeriodServerActionRequestPeriodVolumeBackupTemplate {
            volume_type: None,
        }
    }
}

/// Overrides the volume_type of the snapshot for this volume. If omitted, the volume type of the original volume will be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VolumeType {
    #[serde(rename = "unknown_volume_type")]
    UnknownVolumeType,
    #[serde(rename = "l_ssd")]
    LSsd,
    #[serde(rename = "b_ssd")]
    BSsd,
    #[serde(rename = "unified")]
    Unified,
}

impl Default for VolumeType {
    fn default() -> VolumeType {
        Self::UnknownVolumeType
    }
}
