/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScalewayBaremetalV1ServerRescueServer : Configuration of rescue boot

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayBaremetalV1ServerRescueServer {
    /// Rescue user name
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// Rescue password
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl ScalewayBaremetalV1ServerRescueServer {
    /// Configuration of rescue boot
    pub fn new() -> ScalewayBaremetalV1ServerRescueServer {
        ScalewayBaremetalV1ServerRescueServer {
            user: None,
            password: None,
        }
    }
}
