/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScalewayInstanceV1ServerTypePerVolumeConstraint : Additional volume constraints

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayInstanceV1ServerTypePerVolumeConstraint {
    #[serde(rename = "l_ssd", skip_serializing_if = "Option::is_none")]
    pub l_ssd: Option<Box<crate::models::ScalewayInstanceV1ServerTypePerVolumeConstraintLSsd>>,
}

impl ScalewayInstanceV1ServerTypePerVolumeConstraint {
    /// Additional volume constraints
    pub fn new() -> ScalewayInstanceV1ServerTypePerVolumeConstraint {
        ScalewayInstanceV1ServerTypePerVolumeConstraint { l_ssd: None }
    }
}
