/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScalewayPeriodInstancePeriodV1PeriodServerPeriodAction {
    #[serde(rename = "poweron")]
    Poweron,
    #[serde(rename = "backup")]
    Backup,
    #[serde(rename = "stop_in_place")]
    StopInPlace,
    #[serde(rename = "poweroff")]
    Poweroff,
    #[serde(rename = "terminate")]
    Terminate,
    #[serde(rename = "reboot")]
    Reboot,
}

impl ToString for ScalewayPeriodInstancePeriodV1PeriodServerPeriodAction {
    fn to_string(&self) -> String {
        match self {
            Self::Poweron => String::from("poweron"),
            Self::Backup => String::from("backup"),
            Self::StopInPlace => String::from("stop_in_place"),
            Self::Poweroff => String::from("poweroff"),
            Self::Terminate => String::from("terminate"),
            Self::Reboot => String::from("reboot"),
        }
    }
}

impl Default for ScalewayPeriodInstancePeriodV1PeriodServerPeriodAction {
    fn default() -> ScalewayPeriodInstancePeriodV1PeriodServerPeriodAction {
        Self::Poweron
    }
}
