/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodK8sPeriodV1PeriodExternalNode {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "cluster_url", skip_serializing_if = "Option::is_none")]
    pub cluster_url: Option<String>,
    #[serde(rename = "cluster_version", skip_serializing_if = "Option::is_none")]
    pub cluster_version: Option<String>,
    #[serde(rename = "cluster_ca", skip_serializing_if = "Option::is_none")]
    pub cluster_ca: Option<String>,
    #[serde(rename = "kube_token", skip_serializing_if = "Option::is_none")]
    pub kube_token: Option<String>,
    #[serde(rename = "kubelet_config", skip_serializing_if = "Option::is_none")]
    pub kubelet_config: Option<String>,
}

impl ScalewayPeriodK8sPeriodV1PeriodExternalNode {
    pub fn new() -> ScalewayPeriodK8sPeriodV1PeriodExternalNode {
        ScalewayPeriodK8sPeriodV1PeriodExternalNode {
            id: None,
            name: None,
            cluster_url: None,
            cluster_version: None,
            cluster_ca: None,
            kube_token: None,
            kubelet_config: None,
        }
    }
}
