/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodRdbPeriodV1PeriodListInstanceLogsResponse {
    /// Available logs in a given instance
    #[serde(rename = "instance_logs", skip_serializing_if = "Option::is_none")]
    pub instance_logs: Option<Vec<crate::models::ScalewayPeriodRdbPeriodV1PeriodInstanceLog>>,
}

impl ScalewayPeriodRdbPeriodV1PeriodListInstanceLogsResponse {
    pub fn new() -> ScalewayPeriodRdbPeriodV1PeriodListInstanceLogsResponse {
        ScalewayPeriodRdbPeriodV1PeriodListInstanceLogsResponse {
            instance_logs: None,
        }
    }
}
