/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScalewayPeriodDomainPeriodV2beta1PeriodRecordPeriodType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "A")]
    A,
    #[serde(rename = "AAAA")]
    Aaaa,
    #[serde(rename = "CNAME")]
    Cname,
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "SRV")]
    Srv,
    #[serde(rename = "TLSA")]
    Tlsa,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "NS")]
    Ns,
    #[serde(rename = "PTR")]
    Ptr,
    #[serde(rename = "CAA")]
    Caa,
    #[serde(rename = "ALIAS")]
    Alias,
    #[serde(rename = "LOC")]
    Loc,
    #[serde(rename = "SSHFP")]
    Sshfp,
    #[serde(rename = "HINFO")]
    Hinfo,
    #[serde(rename = "RP")]
    Rp,
    #[serde(rename = "URI")]
    Uri,
    #[serde(rename = "DS")]
    Ds,
    #[serde(rename = "NAPTR")]
    Naptr,
    #[serde(rename = "DNAME")]
    Dname,
}

impl ToString for ScalewayPeriodDomainPeriodV2beta1PeriodRecordPeriodType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::A => String::from("A"),
            Self::Aaaa => String::from("AAAA"),
            Self::Cname => String::from("CNAME"),
            Self::Txt => String::from("TXT"),
            Self::Srv => String::from("SRV"),
            Self::Tlsa => String::from("TLSA"),
            Self::Mx => String::from("MX"),
            Self::Ns => String::from("NS"),
            Self::Ptr => String::from("PTR"),
            Self::Caa => String::from("CAA"),
            Self::Alias => String::from("ALIAS"),
            Self::Loc => String::from("LOC"),
            Self::Sshfp => String::from("SSHFP"),
            Self::Hinfo => String::from("HINFO"),
            Self::Rp => String::from("RP"),
            Self::Uri => String::from("URI"),
            Self::Ds => String::from("DS"),
            Self::Naptr => String::from("NAPTR"),
            Self::Dname => String::from("DNAME"),
        }
    }
}

impl Default for ScalewayPeriodDomainPeriodV2beta1PeriodRecordPeriodType {
    fn default() -> ScalewayPeriodDomainPeriodV2beta1PeriodRecordPeriodType {
        Self::Unknown
    }
}
