/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodRdbPeriodV1PeriodListInstancesResponse {
    /// List all instances available in a given organization/project
    #[serde(rename = "instances", skip_serializing_if = "Option::is_none")]
    pub instances: Option<Vec<crate::models::ScalewayPeriodRdbPeriodV1PeriodInstance>>,
    /// Total count of instances available in a given organization/project
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
}

impl ScalewayPeriodRdbPeriodV1PeriodListInstancesResponse {
    pub fn new() -> ScalewayPeriodRdbPeriodV1PeriodListInstancesResponse {
        ScalewayPeriodRdbPeriodV1PeriodListInstancesResponse {
            instances: None,
            total_count: None,
        }
    }
}
