/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodRdbPeriodV1PeriodListDatabaseBackupsResponse {
    /// List of database backups
    #[serde(rename = "database_backups", skip_serializing_if = "Option::is_none")]
    pub database_backups: Option<Vec<crate::models::ScalewayPeriodRdbPeriodV1PeriodDatabaseBackup>>,
    /// Total count of database backups available
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
}

impl ScalewayPeriodRdbPeriodV1PeriodListDatabaseBackupsResponse {
    pub fn new() -> ScalewayPeriodRdbPeriodV1PeriodListDatabaseBackupsResponse {
        ScalewayPeriodRdbPeriodV1PeriodListDatabaseBackupsResponse {
            database_backups: None,
            total_count: None,
        }
    }
}
