/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodBaremetalPeriodV1PeriodOs {
    /// ID of the OS
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the OS
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Version of the OS
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// URL of this os's logo
    #[serde(rename = "logo_url", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    #[serde(rename = "ssh", skip_serializing_if = "Option::is_none")]
    pub ssh: Option<Box<crate::models::ScalewayBaremetalV1OsSsh>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::ScalewayBaremetalV1OsUser>>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<Box<crate::models::ScalewayBaremetalV1OsPassword>>,
    #[serde(rename = "service_user", skip_serializing_if = "Option::is_none")]
    pub service_user: Option<Box<crate::models::ScalewayBaremetalV1OsServiceUser>>,
    #[serde(rename = "service_password", skip_serializing_if = "Option::is_none")]
    pub service_password: Option<Box<crate::models::ScalewayBaremetalV1OsServicePassword>>,
    /// State of OS
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// License required (check server options for pricing details)
    #[serde(rename = "license_required", skip_serializing_if = "Option::is_none")]
    pub license_required: Option<bool>,
}

impl ScalewayPeriodBaremetalPeriodV1PeriodOs {
    pub fn new() -> ScalewayPeriodBaremetalPeriodV1PeriodOs {
        ScalewayPeriodBaremetalPeriodV1PeriodOs {
            id: None,
            name: None,
            version: None,
            logo_url: None,
            ssh: None,
            user: None,
            password: None,
            service_user: None,
            service_password: None,
            enabled: None,
            license_required: None,
        }
    }
}
