/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalewayPeriodDomainPeriodV2beta1PeriodUpdateDnsZoneNameserversResponse {
    /// The returned DNS zone nameservers
    #[serde(rename = "ns", skip_serializing_if = "Option::is_none")]
    pub ns: Option<Vec<crate::models::ScalewayPeriodDomainPeriodV2beta1PeriodNameserver>>,
}

impl ScalewayPeriodDomainPeriodV2beta1PeriodUpdateDnsZoneNameserversResponse {
    pub fn new() -> ScalewayPeriodDomainPeriodV2beta1PeriodUpdateDnsZoneNameserversResponse {
        ScalewayPeriodDomainPeriodV2beta1PeriodUpdateDnsZoneNameserversResponse { ns: None }
    }
}
