/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// SetVolumeRequestServer : The server attached to the volume

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetVolumeRequestServer {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl SetVolumeRequestServer {
    /// The server attached to the volume
    pub fn new() -> SetVolumeRequestServer {
        SetVolumeRequestServer {
            id: None,
            name: None,
        }
    }
}
