/*
 * Account API
 *
 * # Introduction  The Account API allows you to manage projects. Project is Scaleway’s resource management feature. Designed to help you organize your infrastructure and cloud services, the feature allows resources to be isolated and grouped into specific projects.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetRulesRequest {
    /// Id of policy to update
    #[serde(rename = "policy_id")]
    pub policy_id: String,
    /// Rules of the policy to set
    #[serde(rename = "rules")]
    pub rules: Vec<crate::models::ScalewayPeriodIamPeriodV1alpha1PeriodRuleSpecs>,
}

impl SetRulesRequest {
    pub fn new(
        policy_id: String,
        rules: Vec<crate::models::ScalewayPeriodIamPeriodV1alpha1PeriodRuleSpecs>,
    ) -> SetRulesRequest {
        SetRulesRequest { policy_id, rules }
    }
}
